name: Build and Release

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc make

    - name: Build
      run: |
        gcc -o twitchchat-linux twitchchat.c -pthread -Wall
        chmod +x twitchchat-linux

    - name: Create distribution package
      run: |
        mkdir -p dist
        cp twitchchat-linux dist/
        cp twitchchat.html dist/
        cp twitchchat.css dist/

    - name: Create ZIP archive
      run: |
        cd dist
        zip -r ../twitchchat-linux.zip *

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: twitchchat-linux
        path: twitchchat-linux.zip

  build-windows:
    name: Build for Windows
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up build environment
      run: |
        choco install mingw -y
        refreshenv

    - name: Build
      run: |
        gcc -o twitchchat.exe twitchchat.c -lws2_32 -Wall -D_WIN32_WINNT=0x0600
      shell: bash

    - name: Create distribution package
      run: |
        mkdir -p dist
        cp twitchchat.exe dist/
        cp twitchchat.html dist/
        cp twitchchat.css dist/
      shell: bash

    - name: Create ZIP archive
      run: |
        cd dist
        7z a ../twitchchat-windows.zip *
      shell: bash

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: twitchchat-windows
        path: twitchchat-windows.zip

  build-macos:
    name: Build for macOS
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up build environment
      run: |
        brew install gcc

    - name: Build
      run: |
        gcc -o twitchchat-macos twitchchat.c -pthread -Wall
        chmod +x twitchchat-macos

    - name: Create distribution package
      run: |
        mkdir -p dist
        cp twitchchat-macos dist/
        cp twitchchat.html dist/
        cp twitchchat.css dist/

    - name: Create ZIP archive
      run: |
        cd dist
        zip -r ../twitchchat-macos.zip *

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: twitchchat-macos
        path: twitchchat-macos.zip

  release:
    needs: [build-linux, build-windows, build-macos]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    # This will run even if one of the builds fails
    if: always()

    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./artifacts
      continue-on-error: true

    - name: Get current date and time
      id: date
      run: |
        echo "datetime=$(date +'%d/%m/%Y %I:%M %p')" >> $GITHUB_OUTPUT
        echo "tag=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

    - name: Move artifacts to release directory
      run: |
        mkdir -p release
        find ./artifacts -name "*.zip" -exec mv {} ./release/ \; || true
        ls -la ./release

    - name: Check if any artifacts exist
      id: check_artifacts
      run: |
        if [ "$(ls -A ./release)" ]; then
          echo "has_artifacts=true" >> $GITHUB_OUTPUT
        else
          echo "has_artifacts=false" >> $GITHUB_OUTPUT
        fi

    - name: Create Release
      if: steps.check_artifacts.outputs.has_artifacts == 'true'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.date.outputs.tag }}
        name: Release ${{ steps.date.outputs.datetime }}
        body: |
          ## Twitch Chat Reader - Build ${{ steps.date.outputs.datetime }}
          
          Automated build for all platforms.
          
          ### Downloads (check what's available):
          - `twitchchat-windows.zip` - Windows (x64)
          - `twitchchat-linux.zip` - Linux (x64)
          - `twitchchat-macos.zip` - macOS (x64)
          
          ### What's included:
          - Compiled executable
          - twitchchat.html (web overlay template)
          - twitchchat.css (styling for web overlay)
          
          ### Usage:
          1. Extract the ZIP file
          2. Run the executable
          3. Follow the prompts to connect to Twitch
          
          ### Features:
          - Auto-saves OAuth token for reuse
          - Terminal mode with interactive chat
          - Web overlay mode for OBS
          - Blacklist support (create `blacklist.txt`)
          - Press 'q' to quit gracefully
        files: |
          ./release/*.zip
        draft: false
        prerelease: false
        fail_on_unmatched_files: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
